---
title: "About"
---

I'm an experienced policy data analyst and research programmer interested in direct cash assistance and fiscal federalism. I’m excited about using code-first data science methods to improve and make research workflows reproducible.

In my current role at the Urban Institute, I have a wide policy research and project management portfolio that includes analyzing federal tax policy using the Tax Policy Center Microsimulation Model and applying data privacy methods to administrative tax data.

Prior to joining Urban, I studied economics at Reed College where I also worked as a research assistant, and was an Equity & Policy Intern using research to support housing policy implementation at the Portland Housing Bureau.

#### Experience

**Urban Institute**, Research Associate, July 2019-present

**Reed College**, Research Assistant, Summer 2018

**Portland Housing Bureau**, Equity & Policy Intern, September 2017-June 2018

#### Education

**Reed College** BA in Economics, 2019
